### ISSUE TITLE
grader interface

### ISSUE THREAD

**Issue by kumardeepak** [project-anuvaad/anuvaad-fe-dev-corpus#1]
- once user is logged in successfully
- user can look at the sentences (probably 4 sentences at any given moment)
- Each sentence 'pair' (source and target) is also presented with machine translated sentence against which the sentence pair is compared.
- The rating scale of 1 to 10 is presented against each pair
- User can go back and re-grade the already graded sentence

**Comment by sajish-sasidharan** [comment]
Fixed and merged code into anuvaad branch.
