### ISSUE TITLE
Corrector interface

### ISSUE THREAD

**Issue by kumardeepak** [project-anuvaad/anuvaad-fe-dev-corpus#2]
- once user is logged in successfully
- user can look at the sentences (probably 4 sentences at any given moment)
- user can correct a given sentence pair
- user can fetch sentence translation as a reference and can translate the target sentence.
- user can reject the collected sentence altogether.

This is step comes ahead of "grader"

**Comment by sajish-sasidharan** [comment]
fixed and merged code into anuvaad branch.
